config/routes.rb
Rails.application.routes.draw do
  # Rotas de Upload de Arquivos
  resources :uploads, only: [ :new, :create ]

  # Rotas WEB - Devise padrão
  devise_for :users

  # Namespace separado para API
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for "User", at: "auth"
    end
  end
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :store
  belongs_to :transaction_type
end

app/models/transaction_type.rb
class TransactionType < ApplicationRecord
  has_many :transactions
end

app/models/uploaded_file.rb
class UploadedFile < ApplicationRecord
  has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  include DeviseTokenAuth::Concerns::User
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken

  protected

  def render_error(message, status = :unprocessable_entity)
    render json: { error: message }, status: status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, if: :html_request?
  allow_browser versions: :modern
  protect_from_forgery with: :null_session

  private

  def html_request?
    request.format.html?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @uploaded_file = UploadedFile.new
    # @transactiontype = TransactionType.all
    # @stores = Store.all
    # @transactions = Transaction.all.includes(:store, :transaction_type).order(date: :desc, time: :desc)
    #
     @stores = Store.includes(transactions: :transaction_type)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_user!

  def new
    @uploaded_file = UploadedFile.new
  end

  def create
    @uploaded_file = UploadedFile.new(uploaded_file_params)

    if @uploaded_file.save
      redirect_to root_path, notice: "Arquivo enviado com sucesso."
    else
      render "home/index", status: :unprocessable_entity
    end
  end

  private
  def uploaded_file_params
    params.require(:uploaded_file).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/home/index.html.erb
<h1>Bem Vindo!</h1>
<hr> <br>
<%= render 'uploads/form', upload: @upload %>
<br> <hr> <br>

<h1>Lista de Lojas e Transações</h1>

<% @stores.each do |store| %>
  <div class="store-card">
    <h2><%= store.store_name %></h2>
    <p><strong>Proprietário:</strong> <%= store.owner_name %></p>

    <h3>Transações:</h3>
    <ul>
      <% store.transactions.each do |transaction| %>
        <% tipo = transaction.transaction_type %>
        <% sinal = tipo.signal == '-' ? '-' : '+' %>
        <li>
          <%= tipo.description %>: <%= sinal %>R$ <%= number_to_currency(transaction.value, unit: "", separator: ",", delimiter: ".") %>
        </li>
      <% end %>
    </ul>

    <% saldo = store.transactions.sum do |t| t.transaction_type.signal == '-' ? -t.value : t.value end %>
    <p><strong>Saldo final:</strong> R$ <%= number_to_currency(saldo, unit: "", separator: ",", delimiter: ".") %></p>

    <hr>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cnab Parser" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "shared/navbar" %>

        <!-- Alertas do Devise -->
    <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
        <button class="alert-close" onclick="this.parentElement.style.display='none'">&times;</button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
        <button class="alert-close" onclick="this.parentElement.style.display='none'">&times;</button>
      </div>
    <% end %>

    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    
     <!-- Conteúdo principal -->
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_navbar.html.erb
  <!-- Navbar -->
    <nav class="navbar">
      <%= link_to "Meu App", root_path, class: "navbar-brand" %>
      
      <%= link_to "Home", root_path, class: "nav-link" %>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="user-dropdown">
            <button class="dropdown-toggle" onclick="toggleDropdown()">
              <%= current_user.email %> ▼
            </button>
            <div class="dropdown-menu" id="userDropdown">
              <%= link_to "Perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sair", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
          <%= link_to "Cadastrar", new_user_registration_path, class: "nav-link" %>
        <% end %>
      </ul>
    </nav>

app/views/uploads/_form.html.erb
<%= form_with(model: @uploaded_file, url: uploads_path, local: true) do |form| %>
  <% if @uploaded_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uploaded_file.errors.count, "error") %> prohibited this upload from being saved:</h2>
      <ul>
        <% @uploaded_file.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file, "Selecione o arquivo .txt" %><br>
    <%= form.file_field :file, accept: '.txt' %>
  </div>

  <div class="actions">
    <%= form.submit "Fazer Upload" %>
  </div>
<% end %>

app/views/uploads/new.html.erb
<h1>Fazer Upload .txt</h1>


<%= render "form", upload: @upload %>